### PR TITLE
should not freeze out java thread with undefined method and then make…

### PR DESCRIPTION
**Pull request by abrandoned**
… sure and crazy exceptions in degredation do not stop the rabbit connection thread as well

@quixoten @film42 @mmmries

### CODE REVIEW

**Comment by film42** [comment]
Would it be easier to swap out a lot of our code for concurrent Ruby? It would be more code change but require fewer edge cases like this (I think).

**Comment by abrandoned** [comment]
@film42 definitely want to do that, but this is freezing subscribers right now and preventing releases

**Comment by abrandoned** [comment]
@film42 also requires the assumption that concurrent-ruby won't have any edge cases .... which I don't think is an assumption we can make

**Comment by liveh2o** [comment]
Seems reasonable to me. Let's do the simple cut now, and investigate the larger cut later.

**Comment by quixoten** [comment]
:shipit:

**Pull request merged**
