### PR TITLE
clean up reaper to not check for threadpool "type" and just use pruni…

### PR DESCRIPTION
**Pull request by abrandoned**
…ng interface; update specs; add busy? method to determine if threadpool is busy

may address the concern about the `busy?` method in action_subscriber

@film42 @liveh2o

### CODE REVIEW

**Comment by abrandoned** [comment]
also added an option to name a threadpool during setup

**Comment by liveh2o** [comment]
Failing specs?

**Comment by abrandoned** [comment]
@liveh2o yeah, working on the failing specs; not sure why it fails on MRI 1.9.3 (why the threads don't match); isn't a great spec but digging into what changed

**Comment by liveh2o** [comment]
The change looks fine to me. If it's only 1.9.3 that's failing, I think we can move this forward.

**Comment by abrandoned** [comment]
@liveh2o it was actually a bundler version issue (not the tests but failed because a really old version of bundler) .... cleared it up with a change to travis file

**Comment by liveh2o** [comment]
:+1:

**Comment by film42** [comment]
:+1: :+1:

**Pull request merged**
